# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "html5small"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Run Paint Run Run", "Ruben Verborgh"]
  s.date = "2012-11-04"
  s.description = "Minifier for HTML5 documents"
  s.email = "ruben.verborgh@gmail.com"
  s.executables = ["html5small", "html5small"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/html5small",
    "fixtures/attribute-value-ampersand.html",
    "fixtures/attribute-value-ampersand.html.min",
    "fixtures/attribute-value-quot.html",
    "fixtures/attribute-value-quot.html.min",
    "fixtures/dl.html",
    "fixtures/dl.html.min",
    "fixtures/empty-attributes.html",
    "fixtures/empty-attributes.html.min",
    "fixtures/entities-expand.html",
    "fixtures/entities-expand.html.min",
    "fixtures/entities-no-expand.html",
    "fixtures/entities-no-expand.html.min",
    "fixtures/ie.html",
    "fixtures/ie.html.min",
    "fixtures/lists.html",
    "fixtures/lists.html.min",
    "fixtures/newlines.html",
    "fixtures/newlines.html.min",
    "fixtures/normalise-attribute-name.html",
    "fixtures/normalise-attribute-name.html.min",
    "fixtures/normalise-tag-name.html",
    "fixtures/normalise-tag-name.html.min",
    "fixtures/pre-entities.html",
    "fixtures/pre-entities.html.min",
    "fixtures/pre.html",
    "fixtures/pre.html.min",
    "fixtures/quot-entity.html",
    "fixtures/quot-entity.html.min",
    "fixtures/scripts.html",
    "fixtures/scripts.html.min",
    "fixtures/skeleton.html",
    "fixtures/skeleton.html.min",
    "fixtures/sort-attributes.html",
    "fixtures/sort-attributes.html.min",
    "fixtures/table.html",
    "fixtures/table.html.min",
    "fixtures/tabs.html",
    "fixtures/tabs.html.min",
    "fixtures/whitespace-complex.html",
    "fixtures/whitespace-complex.html.min",
    "fixtures/whitespace-p.html",
    "fixtures/whitespace-p.html.min",
    "html5small.gemspec",
    "lib/html5small.rb",
    "lib/html5small/Minifier.rb",
    "lib/html5small/OptionalTags.rb",
    "spec/htmlsmall_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/RubenVerborgh/HTML5small"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "HTML5small"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<htmlentities>, [">= 4.1.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.5.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<htmlentities>, [">= 4.1.0"])
      s.add_dependency(%q<nokogiri>, [">= 1.5.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<htmlentities>, [">= 4.1.0"])
    s.add_dependency(%q<nokogiri>, [">= 1.5.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

